config/routes.rb
Rails.application.routes.draw do
	root :to => 'pages#home'

	resources :messages

	get		'events/display/:season_id/:episode_id' => 'events#display', :as => :display_events
	get		'events/get_seasons' => 'events#seasons', :as => :get_seasons
	delete 'events/:event_id' => 'events#destroy', :as => :delete_event
	resources :events
	
	get		'episodes' => 'episodes#index', :as => :episodes
	post	'episodes' => 'episodes#create'
	get		'episodes/new' => 'episodes#new', :as => :new_episode
	get		'episodes/new/:season_id' => 'episodes#new'
	get		'episodes/:id' => 'episodes#display', :as => :episode

	get		'pages/about' => 'pages#about'

	get		'statuses/' => 'statuses#index', :as => :statuses
	get		'statuses/:season_id' => 'statuses#display', :as => :statuses_display

	post 	'schemes/:id/assign' => 'schemes#assign'
	get		'schemes/' => 'schemes#index', as: 'schemes'
	get 	'schemes/fetch_schemes' => 'schemes#filter', as: 'fetch_schemes'
	resources :schemes

	get		'seasons/search' => 'seasons#search'
	get		'seasons' => 'seasons#index', :as => :seasons
	post	'seasons' => 'seasons#create'
	get		'seasons/new/:show_id' => 'seasons#new', :as => :new_season_show
	get		'seasons/new' => 'seasons#new', :as => :new_season
	get		'seasons/:id/edit' => 'seasons#edit', :as => :edit_season
	patch 'seasons/:id/publish' => 'seasons#publish', :as => :publish_season
	patch 'seasons/:id/unpublish' => 'seasons#unpublish', :as => :unpublish_season
	get		'seasons/:id' => 'seasons#display', :as => :season
	patch 'seasons/:id' => 'seasons#update'
	put		'seasons/:id' => 'seasons#update'
	delete 'seasons/:id' => 'seasons#destroy'

	get		'shows/new' => 'shows#new', :as => :new_show
	get		'shows/:id' => 'shows#display', :as => :show
	resources :shows

	get		'leagues/new' => 'leagues#new', :as => :new_league
	get		'leagues' => 'leagues#index', :as => :leagues
	get		'leagues/search' => 'leagues#search'
	get		'leagues/:id/invite' => 'leagues#invite', :as => :league_invite
	get		'leagues/:id' => 'leagues#display', :as => :league
	get		'leagues/:id/schemes' => 'leagues#manage_schemes', :as => :league_schemes
	post	'leagues/:id/schemes/:scheme_id' => 'leagues#scheme_action', :as => :league_scheme_action
	resources :leagues
	resources :fantasies, path: 'leagues', :controller => 'leagues'
	post		'leagues/access' => 'leagues#access', :as => :league_access

	post	'users/signup_fb' => 'users#fb_create', :as => :fb_create	
	post	'users/:id/link_fb' => 'users#link_fb', :as => :link_fb
	post	'users/:id/unlink_fb' => 'users#unlink_fb', :as => :unlink_fb
	resources :users
	resources :messages
	
	post	'rosters/:roster_id/add/:contestant_id' => 'rosters#add', :as => :roster_add
	post	'rosters/:roster_id/remove/:contestant_id' => 'rosters#remove', :as => :roster_remove
	get		'rosters/:roster_id/current' => 'rosters#current', :as => :roster_current
	post	'rosters/:league_id' => 'rosters#create', :as => :rosters
	get		'rosters' => 'rosters#index'
	get		'rosters/new' => 'rosters#new', :as => :new_roster
	get		'rosters/:roster_id/edit' => 'rosters#edit', :as => :roster_edit
	get		'rosters/:id' => 'rosters#display', :as => :roster
	patch 'rosters/:id' => 'rosters#update'
	put		'rosters/:id' => 'rosters#update'
	delete 'rosters/:id' => 'rosters#destroy'

	post	'rounds/:league_id' => 'rounds#create', :as => :rounds_create
	get		'rounds/:league_id/:user_id' => 'rounds#index', :as => :rounds
	get		'rounds/:round_id' => 'rounds#display', :as => :round_display
	get		'rounds/:round_id/edit' => 'rounds#edit', :as => :round_edit
	post	'rounds/:round_id/add/:contestant_id' => 'rounds#add', :as => :round_add
	post	'rounds/:round_id/bulk' => 'rounds#bulk_add', :as => :round_bulk_add
	post	'rounds/:round_id/remove/:contestant_id' => 'rounds#remove', :as => :round_remove
	get		'rounds/round/:round_id/save' => 'rounds#save', :as => :round_save
	resources :rounds
	
	get		'contestants/season/:season_id' => 'contestants#index', :as => :contestants_season
	post	'contestants' => 'contestants#create'
	get		'contestants/new/:season_id' => 'contestants#new', :as => :new_contestant
	get		'contestants/:id' => 'contestants#display', :as => :contestant
	post	'contestants/:id' => 'contestants#update'
	delete 'contestants/:id' => 'contestants#destroy'

	get		'login' => 'sessions#new'
	post	'login' => 'sessions#login_attempt'
	post	'login/fb' => 'sessions#facebook_login', :as => :facebook_login
	delete 'login' => 'sessions#logout'

	get		'admin' => 'admin#home'

	# all shows and all seasons lists
	get		'admin/shows' => 'admin#shows', :as => :admin_shows
	get		'admin/seasons' => 'admin#seasons', :as => :admin_seasons

	# API for pulling lists via AJAX
	get		'api/shows'				=> 'application#shows_list',			:as => :api_shows
	get		'api/seasons'			=> 'application#seasons_list',		:as => :api_seasons
	get		'api/episodes'		=> 'application#episodes_list', 	:as => :api_episodes
	get		'api/contestants'	=> 'application#contestants_list', :as => :api_contestants
	get		'api/schemes' 		=> 'application#schemes_list', 		:as => :api_schemes
end

app/models/season.rb
# == Schema Information
#
# Table name: seasons
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  number         :integer
#  show_id        :integer
#  premiere_date  :datetime
#  finale_date    :datetime
#  country_origin :string(255)
#  type           :string(255)
#  description    :text
#  episode_count  :integer
#  image          :string(255)
#  published      :boolean          default(FALSE)
#  expired        :boolean          default(FALSE)
#  created_at     :datetime
#  updated_at     :datetime
#  website        :string(255)
#  network        :string(255)
#

class Season < ActiveRecord::Base
	belongs_to :show, inverse_of: :seasons
	has_many :leagues, inverse_of: :season, dependent: :destroy
	has_many :schemes, through: :show
	has_many :episodes
	has_many :statuses
	has_many :contestants, through: :statuses
	# belongs_to :score

	validates :name, :presence => true, :on => :create
	validates :premiere_date, :presence => true, :on => :create

	def full_name
		show_name = self.show.name
		full_name = "#{show_name}: #{self.name}"
	end

	private
	
	def self.top_three
		# This model method is called in Pages#home to give list of the three top shows
		
		Season.where(expired: false).order("premiere_date ASC").last(3)
	end

	def self.seasons_list
		# This model method is for populating Create League's drop-down menu
		@seasons_list = Season.uniq.order("name ASC").each.map {|s| [s.name, s.id] }
		@seasons_list.unshift(["All Seasons", "All"])
	end
	def self.select_season
		# This model method is for populating Create League's drop-down menu
		@seasons_list = Season.where(expired: false).each.map {|s| [s.name, s.id]}
	end

	# check method if season can be edited

	def self.list_by_show(show_id)
		seasons_show = Season.where(show_id: show_id)	
	end

	def get_points_by_season(season_id)
		season = Season.find(season_id)
		episodes_list = Episode.where(season_id: season_id)
		@points_season = []
		episode_list.each do |episode|
			@points_season << episode.points
		end
		return @points_season
	end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
	before_action :check_if_admin, only: [:new, :edit, :update, :publish, :unpublish, :destroy]
	before_action :check_if_logged_in, only: [:display]
	layout "admin", except: [:display]

	def index
		@current_seasons = Season.where(:expired => :false).order("premiere_date ASC")
		@past_seasons = Season.where(:expired => :true).order("premiere_date DESC")
		@current_date = DateTime.now.strftime("%B %d, %Y")
	end

	def new
		@season = Season.new(:show_id => params[:show_id])
	end

	def create
		@season = Season.new season_params
		if @season.save
			flash[:notice_show] = "You've successfully added #{@season.show.name}: #{@season.name}."
			flash[:color] = "alert-success"
			redirect_to contestants_season_path(@season.id)
		else
			flash[:notice] = "Something went wrong, please try again."
			flash[:color] = "alert-danger"
			render :new
		end
	end

	def edit
		@season = Season.find(params[:id])
		params[:premiere_time] = @season.premiere_date.strftime("%I:%M")
	end
	
	def update
		@season = Season.find(params[:id])
		if @season.update season_params
			redirect_to admin_seasons_path
		else
			render :edit
		end
	end

	def publish
		@season = Season.find(params[:id])
		if @season.update(published: true)
			flash[:notice] = "#{@season.show.name}: #{@season.name} is now published."
			flash[:color] = "alert-success"
			redirect_to admin_seasons_path
		else
			flash[:notice] = "Something went wrong, please try again."
			flash[:color] = "alert-warning"
			redirect_to admin_seasons_path
		end
	end

	def unpublish
		@season = Season.find(params[:id])
		if @season.leagues.count > 0
			flash[:notice] = "#{@season.show.name}: #{@season.name} cannot be unpublished because leagues for this season already exist."
			flash[:color] = "alert-danger"
			redirect_to admin_seasons_path
		elsif @season.update(published: false)
			flash[:notice] = "#{@season.show.name}: #{@season.name} is now hidden from the public."
			flash[:color] = "alert-success"
			redirect_to admin_seasons_path
		else
			flash[:notice] = "Something went wrong, please try again."
			flash[:color] = "alert-danger"
			redirect_to admin_seasons_path
		end
	end

	def destroy
		@season = Season.find params[:id]
		if @season.leagues.count > 0
			flash[:notice] = "#{@season.show.name}: #{@season.name} cannot be deleted because leagues for this season already exist."
			flash[:color] = "alert-danger"
			redirect_to admin_seasons_path
		elsif	@season.destroy
			flash[:notice] = "#{@season.show.name}: #{@season.name} has been successfully deleted."
			flash[:color] = "alert-success"
			redirect_to admin_seasons_path
		else
			flash[:notice] = "Something went wrong, please try again."
			flash[:color] = "alert-danger"
			redirect_to admin_seasons_path
		end
	end

	def display
		@season = Season.includes(:show, :statuses, :contestants).find(params[:id])
		@statuses = @season.statuses
		@show = @season.show
		@rules_collection = get_schemes(@show)
		@contestants = @season.contestants.order("name ASC")

		@contestant_status_collection = []
		@contestants.each_with_index do |contestant, i|
			if contestant.present?
				@contestant_status_collection[i] = ""
			else
				@contestant_status_collection[i] = "eliminated"
			end
		end
		@contestants_ranking = @season.contestants.includes(:events).order(:name)

		render_admin
	end
	
	def manage
		
	end

	private

	def season_params
		new_premiere_date = "#{params[:season][:premiere_date]} #{params[:season][:premiere_time]}:00"
		params[:season][:premiere_date] = new_premiere_date
		params.require(:season).permit(:name, :number, :show_id, :premiere_date, :finale_date, :country_origin, :type, :description, :episode_count, :image, :website, :network, :published, :expired)
	end

end

app/views/seasons/_admin.html.haml
.panel.panel-default
	.panel-heading
		.panel-title.row
			.col-lg-10
				%h2 Manage Seasons
			.col-lg-2.text-right
				= link_to "Add New Season", new_season_path, class:"btn btn-default btn-sm"
	.panel-body
		%table.table.table-hover
			/ Error Messages
			.row.form-group
				- if flash[:notice] && flash[:color] == "valid"
					.alert.alert-success{:role => "alert"}= flash[:notice]
				- elsif flash[:notice] && flash[:color] == "invalid"
					.alert.alert-warning{:role => "alert"}= flash[:notice]
				- elsif flash[:notice] && flash[:color] == "prohibited"
					.alert.alert-danger{:role => "alert"}= flash[:notice]
			/ End Error Messages
			%h4 
				Current 
				= pluralize_without_count(@current_seasons.count, "Season", text = nil)
			%thead
				%tr
					%th.col-sm-3 Season Name
					/ column 1
					%th.col-sm-1 Status
					/ column 2
					%th.col-sm-1 Premiere
					/ column 3
					%th.col-sm-1 Finale
					%th.col-sm-3 Actions
					/ column 4
					%th.col-sm-1 
					%th.col-sm-2 Events
					/ column 6
					%th.col-sm-1 Contestants
					/ column 7
			%tbody
				- @current_seasons.each do |season|
					%tr
						/ column 1
						%td
							= link_to "#{season.show.name}: #{season.name}", season_path(season.id)
						/ column 2
						%td
							- if season.premiere_date < @current_date
								Commenced
							- elsif season.published? == false
								Unpublished
							- else
								Draft Open
						%td= season.premiere_date.strftime("%D")
						/ column 3
						%td= season.finale_date.strftime("%D")
						%td
							= link_to "View", season_path(season.id), class:"btn btn-sm btn-default"
							= link_to "Edit", edit_season_path(season.id), class:"btn btn-sm btn-default"
							= link_to "Delete", season_path(season.id), :method => "delete", :action => "destroy", :data => {:confirm => "Are you sure you want to delete this season?"}, class:"btn btn-sm btn-default"
						%td
							- if season.published? 
								= link_to "Unpublish", unpublish_season_path(season.id), :method => "patch", :data => {:confirm => "Are you sure you want to unpublish this season?"}, class:"btn btn-sm btn-default"
							- else
								= link_to "Publish", publish_season_path(season.id), :method => "patch", class:"btn btn-sm btn-default"
						%td 
							= link_to "Track", edit_season_path(season.id), class:"btn btn-sm btn-default"
							= link_to "View", season_path(season.id), class:"btn btn-sm btn-default"
						%td
							= link_to "View", contestants_season_path(season.id), class:"btn btn-sm btn-default"
	.panel-body
		%table.table.table-hover
			%h4 
				Past 
				= pluralize_without_count(@past_seasons.count, "Season", text = nil)
			%thead
				%tr
					/ column 1
					%th.col-sm-3 Season Name
					/ column 2
					%th.col-sm-1 Status
					/ column 3
					%th.col-sm-1 Premiered
					/ column 4
					%th.col-sm-1 Finale Date
					/ column 5
					%th.col-sm-3 Actions
					/ column 6
					%th.col-sm-3 Statistics
			%tbody
				- @past_seasons.each do |season|
					%tr
						/ column 1
						%td
							= link_to "#{season.show.name}: #{season.name}", season_path(season.id)
						/ column 2
						%td
							- if season.expired == true
								Completed
							- else
								- if season.premiere_date < @current_date
									Commenced
								- elsif season.published? == false
									Unpublished
								- else
									Draft Open
						/ column 3
						%td= season.premiere_date.strftime("%D")
						/ column 4
						%td= season.finale_date.strftime("%D")
						/ column 5
						%td
							= link_to "View", season_path(season.id), class:"btn btn-sm btn-default"
							= link_to "Contestants", contestants_season_path(season.id), class:"btn btn-sm btn-default"
						%td

app/views/seasons/_current_seasons.html.haml
.panel.panel-default
	.panel-body
		.panel-heading
			%h2 Current Seasons
		- @current_seasons.each do |season|
			.col-sm-4.col-md-3
				.thumbnail
					%img.img-thumbnail{:src => season.image}/
					.caption.caption-lg
						%h4
							= season.show.name + ": "
							= season.name
						%p
							Starts: #{season.premiere_date.strftime("%B %d")}
						%p= link_to "Explore Season", season_path(season.id), class:"btn btn-primary"

app/views/seasons/_current_shows.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="panel-heading">
			<h2>Current Shows</h2>
		</div>
		<% @shows.each do |show| %>
			<div class="col-sm-4 col-md-3">
				<div class="thumbnail">
					<%= link_to image_tag(show.image, :alt => show.name), show_path(show.id), class:"img-thumbnail" %>
					<div class="caption caption-lg">
						<h4><%= show.name %></h4>
						<p>Starts: <%= show.premiere_date.strftime("%B %d") %></p>
						<p><%= link_to "Explore Show", show_path(show.id), class:"btn btn-primary" %></p>
					</div>
				</div>
			</div>    
		<% end %>
	</div>
</div>

app/views/seasons/_featured_seasons.html.haml
.panel.panel-default
	.panel-body
		.col-md-12
			%h2 Featured Shows		
	#carousel-features-generic.carousel.slide{"data-ride" => "carousel"}
		/ Indicators
		%ol.carousel-indicators
			%li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
			%li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
			%li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
		/ Wrapper for slides
		.carousel-inner
			- @featured_seasons.each_with_index do |season, i|
				- if i == 0
					.item.carousel-img.active
						%img{:alt => season.name, :src => season.image}/
						.carousel-caption
							%h2
								= season.show.name + ": "
								= season.name
				- else
					.item.carousel-img
						%img{:alt => season.name, :src => season.image}/
						.carousel-caption
							%h2
								= season.show.name + ": "
								= season.name	

		/ Controls
		%a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
			%span.glyphicon.glyphicon-chevron-left
		%a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
			%span.glyphicon.glyphicon-chevron-right

app/views/seasons/_featured_shows.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="col-md-12">
			<h1>Featured Shows</h1>
			<p>Here are some of the most popular shows at the moment:</p>
			<div class="row">
				<% @featured_seasons.each do |show| %>
					<div class="col-sm-4 col-md-3">
						<div class="thumbnail">
							<div class="img-thumbnail-container">
								<img src="<%= show.image %>" class="img-thumbnail"/>						
							</div>
							<div class="caption">
								<h4><%= show.name %></h4>
								<p>Starts: <%= show.premiere_date.strftime("%B %d") %></p>
								<p><%= link_to(content_tag(:button, "Explore Show", class:'btn btn-primary'), show_path(show.id)) %></p>
							</div>
						</div>
					</div>
				<% end %>
			</div>			
			<%= link_to('Browse All Shows', shows_path, class: "btn btn-default btn-lg") %>
		</div>
	</div>
</div>

app/views/seasons/_form.html.haml
.panel.panel-default
	.panel-body
		.col-lg-12.col-md-12.col-sm-12
			- if params[:id]
				%h2 Edit Season
			- elsif params[:show_id]
				%h2= "Add New Season: #{@season.show.name}"
			- else
				%h2 Add New Season
			#new-season-form.col-lg-4.col-md-6.col-sm-6
				= form_for(@season, class: "form-horizontal", role: "form") do |f|
					/ Error Messages
					.row.form-group
						- if flash[:notice] && flash[:color] == "valid"
							.alert.alert-success{role: "alert"}= flash[:notice]
						- elsif flash[:notice] && flash[:color] == "invalid"
							.alert.alert-warning{role: "alert"}= flash[:notice]
						- elsif flash[:notice] && flash[:color] == "prohibited"
							.alert.alert-danger{role: "alert"}
								%p= flash[:notice]
								- if @season.errors.any?
									%p
										= pluralize(@season.errors.count, "error")
										prohibited this season from being saved:
									%ul
										- @season.errors.full_messages.each do |message|
											%li= message
					/ End Error Messages
					/ Form Portion
					.row.form-group
						= f.label :show_id
						- if @season.id
							= f.select(:show_id, options_for_select(Show.select_show, @season.show.id), {}, {class: "form-control", required: true})
						- elsif @season.show_id
							= f.select(:show_id, options_for_select(Show.select_show_all, @season.show.id), {selected: @season.show_id}, {class: "form-control", required: true})
						- else
							= f.select(:show_id, options_for_select(Show.select_show_all), {include_blank: "Select a show"}, {class: "form-control", required: true})
					.row.form-group
						= f.label :title
						= f.text_field :name, class: "form-control", required: true, placeholder: "Enter season\'s title"
					.row.form-group
						= f.label :season_number
						= f.number_field :number, class: "form-control", required: true, placeholder: 0
					.row.form-group
						= f.label :premiere_date
						= f.date_field :premiere_date, class: "form-control"
						%input{:type => "time", :name => "season[premiere_time]", class: "form-control", :value => params[:premiere_time]}
					.row.form-group
						= f.label :finale_date
						= f.date_field :finale_date, class: "form-control"
					.row.form-group
						= f.label :country_origin
						= f.text_field :country_origin, class: "form-control"
					.row.form-group
						= f.label :type
						= f.text_field :type, class: "form-control", placeholder: "Romance, Drama, Race"
					.row.form-group
						= f.label :description
						= f.text_area :description, class: "form-control", placeholder: "Enter description here", rows: 5
					.row.form-group
						= f.label :image
						= f.text_field :image, class: "form-control", placeholder: "url"
					.row.form-group
						= f.label :episode_count
						= f.number_field :episode_count, min: 8, max: 30, class: "form-control", placeholder: 10
					.row.form-group
						= f.label :website
						= f.text_field :website, class: "form-control", placeholder: "url"					
					.row.form-group
						= f.label :network
						= f.text_field :network, class: "form-control", placeholder: "ABC/NBC.CBS"			
					.row.form-group
						- if @season.id
							= f.check_box :published
							= f.label :published
						- else		
							= f.check_box :published, value: true
							= f.label :publish_now?
					.row.form-group
						- if @season.id
							= f.check_box :expired
						- else
							= f.check_box :expired, :display => "none", value: false
						
						= f.label :expired
					.row.form-group.actions
						- if params[:id]
							= f.submit "Update season", class: "btn btn-primary btn-md"
							= link_to "Cancel", admin_seasons_path, class: "btn btn-default btn-md"
						- else
							= f.submit "Save season", class: "btn btn-primary btn-md"
							= link_to "Cancel", admin_seasons_path, class: "btn btn-default btn-md"
					/ End Form portion
			/ End sign-up-form
		/ End col-md-12
	/ End panel-body
/ End panel panel-default

app/views/seasons/_past_seasons.html.haml
.panel.panel-default
	.panel-body
		.panel-heading
			%h2 Past Seasons
		- @past_seasons.each do |season|
			.col-sm-4.col-md-3
				.thumbnail
					%img.img-thumbnail{:src => season.image}/
					.caption.caption-lg
						%h4
							= season.full_name
						%p
							Premiered: #{season.premiere_date.strftime("%B %d, %Y")}
						%p= link_to "Explore Season", season_path(season.id), class:"btn btn-primary"

app/views/seasons/_past_shows.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="panel-heading">
			<h2>Past Shows</h2>
		</div>
		<% @past_shows.each do |show| %>
			<div class="col-sm-4 col-md-3">
				<div class="thumbnail">
					<img src="<%= show.image %>" class="img-thumbnail">
					<div class="caption caption-lg">
						<h4><%= show.name %></h4>
						<p>Premiered: <%= show.premiere_date.strftime("%B %d, %Y") %></p>
						<p><%= link_to "Explore Show", show_path(show.id), class:"btn btn-primary" %></p>
					</div>
				</div>
			</div>    
		<% end %>
	</div>
</div>

app/views/seasons/display.html.haml
.panel.panel-default#season-display
	.panel-body
		.col-lg-7
			%h2
				= @season.show.name + ": "
				= @season.name
			%p
				Premiere Date:
				= @season.premiere_date.strftime("%D")
			= render "shows/scoring_system"
		.col-lg-5.text-right
			= link_to "Back to #{@season.show.name}", show_path(@season.show.id), class:"btn btn-default btn-sm"
			= link_to "Back to All Shows", shows_path, class:"btn btn-default btn-sm"
	.panel-body
		.col-lg-12
			%h4 Contestants
			- @contestants.each_with_index do |contestant, i|
				.col-xs-3.col-sm-2.col-md-2.col-lg-2
					.thumbnail.contestant-thumbnail{class: "#{@contestant_status_collection[i]}"}
						%img.half-res{:src => "#{contestant.image}", :alt => "#{contestant.name}"}/
						.veil
							= @contestant_status_collection[i].upcase
						.caption
							.contestant-name= contestant.name
		.col-lg-12.text-right
			%p.small Photos courtesy of #{ link_to @season.network, @season.website }
	- if @season.episodes.any?
		.panel-body
			.col-lg-12
				%h4 Score By Episode
				%table.table.table-hover
					%thead
						%tr
							%th.col-lg-2 Contestants
							- @season.episodes.count.times do |i|
								%th= i+1
							%th.col-lg-1 Status
					%tbody
						- @contestants_ranking.each_with_index do |contestant, index|
							%tr
								%td
									= contestant.name
								- @season.episodes.each_with_index do |episode, i|
									%td
										= link_to contestant.calculate_points_per_episode(episode.id), episode_path(episode.id)
								%td= @contestant_status_collection[index].capitalize
	- if @statuses
		.panel-body
			.col-lg-12
				%h4 Contestant Status
				%table.table.table-hover
					%thead
						%th Contestant
						%th Present
						%th Eliminated Episode
					- @statuses.each do |status|
						%tbody
							%tr
								%td= status.contestant.name
								%td= status.present
								%td= status.eliminated_episode_id

app/views/seasons/edit.html.erb
<%= render 'form' %>

app/views/seasons/index.html.haml
= render partial: "current_seasons"
= render partial: "past_seasons"

app/views/seasons/new.html.erb
<%= render 'form' %>

app/views/seasons/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="col-md-6">
			<h2><%= @show.name %></h2>
			<h3><%= @show.franchise.name %></h3>
		</div>
		<div class="col-md-6 text-right text-bottom">
			<% if @current_user && @current_user.admin? %>
				<%= link_to "Edit Show", edit_show_path(@show.id), class:"btn btn-default" %>
				<%= link_to "Edit Contestants", contestants_show_path(@show.id), class:"btn btn-default" %>
				<%= link_to "Back to Shows", shows_path, class:"btn btn-default" %>
			<% end %>
		</div>
		<div class="panel-body">
			<div class="col-md-9 col-md-push-3">
				<div class="panel-body">
					<h2>Contestants</h2>
						<% @contestants.each do |contestant| %>
							<div class="col-sm-6 col-md-4">
								<div class="thumbnail tmbn-contestant">
									<%= image_tag contestant.image %>
									<div class="caption">
										<h4><%= contestant.name %><%= contestant.status %></h4>
										Age: <%= contestant.age %>
										<br>
										Occupation: <%= contestant.occupation %>
									</div>	
								</div>
							</div>

						<% end %>
					</div>
				</div>
				<div class="col-md-3 col-md-pull-9">
					<div class="row">
						<div class="col-md-12">
							<%= image_tag @show.image, class:"img-thumbnail" %>					
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<h4>Description: </h4>
							<%= @show.description %>					
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<% if @show.expired == true %>
								<h4>Premiered: <%= @show.premiere_date.strftime("%B %d, %Y") %></h4>
								<p><%= @show.description %></p>
							<% else %>
								<h4>Premieres: <%= @show.premiere_date.strftime("%B %d") %></h4>
								<%= button_to "Find a league for this show", leagues_path, class:"btn btn-default" %> <!-- FIXME -->
							<% end %>				
						</div>
					</div>
				</div>
				<!-- end -->
		</div>
	</div>
</div>