config/routes.rb
Rails.application.routes.draw do
	root :to => 'pages#home'

	resources :messages

	get		'events/display/:season_id/:episode_id' => 'events#display', :as => :display_events
	get		'events/get_seasons' => 'events#seasons', :as => :get_seasons
	delete 'events/:event_id' => 'events#destroy', :as => :delete_event
	resources :events
	
	get		'episodes' => 'episodes#index', :as => :episodes
	post	'episodes' => 'episodes#create'
	get		'episodes/new' => 'episodes#new', :as => :new_episode
	get		'episodes/new/:season_id' => 'episodes#new'
	get		'episodes/:id' => 'episodes#display', :as => :episode

	get		'pages/about' => 'pages#about'

	get		'statuses/' => 'statuses#index', :as => :statuses
	get		'statuses/:season_id' => 'statuses#display', :as => :statuses_display

	post 	'schemes/:id/assign' => 'schemes#assign'
	get		'schemes/' => 'schemes#index', as: 'schemes'
	get 	'schemes/fetch_schemes' => 'schemes#filter', as: 'fetch_schemes'
	resources :schemes

	get		'seasons/search' => 'seasons#search'
	get		'seasons' => 'seasons#index', :as => :seasons
	post	'seasons' => 'seasons#create'
	get		'seasons/new/:show_id' => 'seasons#new', :as => :new_season_show
	get		'seasons/new' => 'seasons#new', :as => :new_season
	get		'seasons/:id/edit' => 'seasons#edit', :as => :edit_season
	patch 'seasons/:id/publish' => 'seasons#publish', :as => :publish_season
	patch 'seasons/:id/unpublish' => 'seasons#unpublish', :as => :unpublish_season
	get		'seasons/:id' => 'seasons#display', :as => :season
	patch 'seasons/:id' => 'seasons#update'
	put		'seasons/:id' => 'seasons#update'
	delete 'seasons/:id' => 'seasons#destroy'

	get		'shows/new' => 'shows#new', :as => :new_show
	get		'shows/:id' => 'shows#display', :as => :show
	resources :shows

	get		'leagues/new' => 'leagues#new', :as => :new_league
	get		'leagues' => 'leagues#index', :as => :leagues
	get		'leagues/search' => 'leagues#search'
	get		'leagues/:id/invite' => 'leagues#invite', :as => :league_invite
	get		'leagues/:id' => 'leagues#display', :as => :league
	get		'leagues/:id/schemes' => 'leagues#manage_schemes', :as => :league_schemes
	post	'leagues/:id/schemes/:scheme_id' => 'leagues#scheme_action', :as => :league_scheme_action
	resources :leagues
	resources :fantasies, path: 'leagues', :controller => 'leagues'
	post		'leagues/access' => 'leagues#access', :as => :league_access

	post	'users/signup_fb' => 'users#fb_create', :as => :fb_create	
	post	'users/:id/link_fb' => 'users#link_fb', :as => :link_fb
	post	'users/:id/unlink_fb' => 'users#unlink_fb', :as => :unlink_fb
	resources :users
	resources :messages
	
	post	'rosters/:roster_id/add/:contestant_id' => 'rosters#add', :as => :roster_add
	post	'rosters/:roster_id/remove/:contestant_id' => 'rosters#remove', :as => :roster_remove
	get		'rosters/:roster_id/current' => 'rosters#current', :as => :roster_current
	post	'rosters/:league_id' => 'rosters#create', :as => :rosters
	get		'rosters' => 'rosters#index'
	get		'rosters/new' => 'rosters#new', :as => :new_roster
	get		'rosters/:roster_id/edit' => 'rosters#edit', :as => :roster_edit
	get		'rosters/:id' => 'rosters#display', :as => :roster
	patch 'rosters/:id' => 'rosters#update'
	put		'rosters/:id' => 'rosters#update'
	delete 'rosters/:id' => 'rosters#destroy'

	post	'rounds/:league_id' => 'rounds#create', :as => :rounds_create
	get		'rounds/:league_id/:user_id' => 'rounds#index', :as => :rounds
	get		'rounds/:round_id' => 'rounds#display', :as => :round_display
	get		'rounds/:round_id/edit' => 'rounds#edit', :as => :round_edit
	post	'rounds/:round_id/add/:contestant_id' => 'rounds#add', :as => :round_add
	post	'rounds/:round_id/bulk' => 'rounds#bulk_add', :as => :round_bulk_add
	post	'rounds/:round_id/remove/:contestant_id' => 'rounds#remove', :as => :round_remove
	get		'rounds/round/:round_id/save' => 'rounds#save', :as => :round_save
	resources :rounds
	
	get		'contestants/season/:season_id' => 'contestants#index', :as => :contestants_season
	post	'contestants' => 'contestants#create'
	get		'contestants/new/:season_id' => 'contestants#new', :as => :new_contestant
	get		'contestants/:id' => 'contestants#display', :as => :contestant
	post	'contestants/:id' => 'contestants#update'
	delete 'contestants/:id' => 'contestants#destroy'

	get		'login' => 'sessions#new'
	post	'login' => 'sessions#login_attempt'
	post	'login/fb' => 'sessions#facebook_login', :as => :facebook_login
	delete 'login' => 'sessions#logout'

	get		'admin' => 'admin#home'

	# all shows and all seasons lists
	get		'admin/shows' => 'admin#shows', :as => :admin_shows
	get		'admin/seasons' => 'admin#seasons', :as => :admin_seasons

	# API for pulling lists via AJAX
	get		'api/shows'				=> 'application#shows_list',			:as => :api_shows
	get		'api/seasons'			=> 'application#seasons_list',		:as => :api_seasons
	get		'api/episodes'		=> 'application#episodes_list', 	:as => :api_episodes
	get		'api/contestants'	=> 'application#contestants_list', :as => :api_contestants
	get		'api/schemes' 		=> 'application#schemes_list', 		:as => :api_schemes
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  messagetype    :string(255)
#  messagecomment :text
#  created_at     :datetime
#  updated_at     :datetime
#  page_url       :string(255)
#  resolved       :boolean          default(FALSE)
#

class Message < ActiveRecord::Base
	belongs_to :user, inverse_of: :messages

	validates :user_id, presence: true, :on => :create
	validates :messagetype, presence: true, :on => :create
	validates :messagecomment, presence: true, :on => :create
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	layout "admin"
	before_action :check_if_logged_in
	before_action :check_if_admin

	def index
		@unresolved_messages = Message.where(resolved: false).order(created_at: :asc)
		@resolved_messages = Message.where(resolved: true).order(created_at: :asc)
	end

	def edit
		@message = Message.includes(:user).find(params[:id])
		@username = @message.user.username
	end


	def update
		@message = Message.find(params[:id])
		if @message.save
			flash[:notice] = "Message has been successfully updated."
			# Once someone signs up, they currently need to log in. Better to have automatically log-in?
			flash[:color] = "alert-success"
		else
			flash[:notice] = "Something went wrong - message could not be updated."
			flash[:color] = "alert-warning"
			render :new
		end	
	end

	def create
		@message = Message.new
		@message.user_id = params[:message][:user_id]
		@message.messagetype = params[:message][:messagetype]
		@message.messagecomment = params[:message][:messagecomment]
		@message.page_url = params[:message][:pageurl]
		if @message.save
			respond_to do |format|
				format.js {
					render :json => {
						:success => "Thank you, your comment has been submitted."
					}
				}
			end
		else
			respond_to do |format|
				format.json { 
					render :json => { :error => "You must be logged in to submit a comment." }, 
					:status => 422 
				}
				format.js { 
					render :json => @person.errors, :status => :unprocessable_entity }
			end
		end

	end

end

app/views/messages/_feedback_form.html.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} &times;
				%h4#myModalLabel.modal-title Feedback
			.modal-body
				= form_for(@message, class: "form-horizontal"), :role => "form", :html => {:multipart => true}) do |f|
					.row.form-group
						= f.label :user_id
						= f.number_field :user_id, placeholder: @current_user.username, value: @current_user.id
					.row.form-group
						= f.label :type
						= f.field :type
					.row.form-group
						= f.label :message
						= f.field :type
			.modal-footer
				%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
				%button.btn.btn-primary{:type => "button"} Save changes

app/views/messages/_form.html.haml
.panel.panel-default
	.panel-body
		.col-lg-12.col-md-12
			- if params[:id]
				%h2
					Edit Message
			#edit-message-form.col-lg-4.col-md-6.col-sm-6
				-# Form 
				= form_for(@message, class:"form-horizontal", :role => "form", :html => {:multipart => true}) do |f|
					- if @message.errors.any?
						.row.form-group
							.alert.alert-warning{:role => "alert"}
								%p= flash[:notice]
								%ul
									- @message.errors.full_messages.each do |msg|
										%li= msg
					/ Form Portion
					%fieldset{:disabled => "disabled"}
						.row.form-group.disabled
							= f.label :user_id, "User", class:"control-label"
							= f.number_field :user_id, class: "form-control", :id => "disabledTextInput", :autofocus => false
							= @username
					

app/views/messages/edit.html.haml
= render partial: "form"

app/views/messages/index.html.haml
- if @unresolved_messages.present?
	%table.table.table-condensed
		%thead
			%th.col-lg-1 Date
			%th.col-lg-1 Reporter
			%th.col-lg.1 Type
			%th.col-lg-7 Message
			%th.col-lg-1 Status
			%th.col-lg-1 Action
		%tbody
			- @unresolved_messages.each do |message|
				%tr
					%td= message.created_at.strftime("%D %H:%I %Z")
					%td
						=message.id 
						=message.id
					%td= message.messagetype
					%td= message.messagecomment
					%td= message.resolved
					%td= link_to "Edit", edit_message_path(message.id), class: "btn btn-default btn-sm"