config/routes.rb
Rails.application.routes.draw do
	root :to => 'pages#home'

	resources :messages

	get		'events/display/:season_id/:episode_id' => 'events#display', :as => :display_events
	get		'events/get_seasons' => 'events#seasons', :as => :get_seasons
	delete 'events/:event_id' => 'events#destroy', :as => :delete_event
	resources :events
	
	get		'episodes' => 'episodes#index', :as => :episodes
	post	'episodes' => 'episodes#create'
	get		'episodes/new' => 'episodes#new', :as => :new_episode
	get		'episodes/new/:season_id' => 'episodes#new'
	get		'episodes/:id' => 'episodes#display', :as => :episode

	get		'pages/about' => 'pages#about'

	get		'statuses/' => 'statuses#index', :as => :statuses
	get		'statuses/:season_id' => 'statuses#display', :as => :statuses_display

	post 	'schemes/:id/assign' => 'schemes#assign'
	get		'schemes/' => 'schemes#index', as: 'schemes'
	get 	'schemes/fetch_schemes' => 'schemes#filter', as: 'fetch_schemes'
	resources :schemes

	get		'seasons/search' => 'seasons#search'
	get		'seasons' => 'seasons#index', :as => :seasons
	post	'seasons' => 'seasons#create'
	get		'seasons/new/:show_id' => 'seasons#new', :as => :new_season_show
	get		'seasons/new' => 'seasons#new', :as => :new_season
	get		'seasons/:id/edit' => 'seasons#edit', :as => :edit_season
	patch 'seasons/:id/publish' => 'seasons#publish', :as => :publish_season
	patch 'seasons/:id/unpublish' => 'seasons#unpublish', :as => :unpublish_season
	get		'seasons/:id' => 'seasons#display', :as => :season
	patch 'seasons/:id' => 'seasons#update'
	put		'seasons/:id' => 'seasons#update'
	delete 'seasons/:id' => 'seasons#destroy'

	get		'shows/new' => 'shows#new', :as => :new_show
	get		'shows/:id' => 'shows#display', :as => :show
	resources :shows

	get		'leagues/new' => 'leagues#new', :as => :new_league
	get		'leagues' => 'leagues#index', :as => :leagues
	get		'leagues/search' => 'leagues#search'
	get		'leagues/:id/invite' => 'leagues#invite', :as => :league_invite
	get		'leagues/:id' => 'leagues#display', :as => :league
	get		'leagues/:id/schemes' => 'leagues#manage_schemes', :as => :league_schemes
	post	'leagues/:id/schemes/:scheme_id' => 'leagues#scheme_action', :as => :league_scheme_action
	resources :leagues
	resources :fantasies, path: 'leagues', :controller => 'leagues'
	post		'leagues/access' => 'leagues#access', :as => :league_access

	post	'users/signup_fb' => 'users#fb_create', :as => :fb_create	
	post	'users/:id/link_fb' => 'users#link_fb', :as => :link_fb
	post	'users/:id/unlink_fb' => 'users#unlink_fb', :as => :unlink_fb
	resources :users
	resources :messages
	
	post	'rosters/:roster_id/add/:contestant_id' => 'rosters#add', :as => :roster_add
	post	'rosters/:roster_id/remove/:contestant_id' => 'rosters#remove', :as => :roster_remove
	get		'rosters/:roster_id/current' => 'rosters#current', :as => :roster_current
	post	'rosters/:league_id' => 'rosters#create', :as => :rosters
	get		'rosters' => 'rosters#index'
	get		'rosters/new' => 'rosters#new', :as => :new_roster
	get		'rosters/:roster_id/edit' => 'rosters#edit', :as => :roster_edit
	get		'rosters/:id' => 'rosters#display', :as => :roster
	patch 'rosters/:id' => 'rosters#update'
	put		'rosters/:id' => 'rosters#update'
	delete 'rosters/:id' => 'rosters#destroy'

	post	'rounds/:league_id' => 'rounds#create', :as => :rounds_create
	get		'rounds/:league_id/:user_id' => 'rounds#index', :as => :rounds
	get		'rounds/:round_id' => 'rounds#display', :as => :round_display
	get		'rounds/:round_id/edit' => 'rounds#edit', :as => :round_edit
	post	'rounds/:round_id/add/:contestant_id' => 'rounds#add', :as => :round_add
	post	'rounds/:round_id/bulk' => 'rounds#bulk_add', :as => :round_bulk_add
	post	'rounds/:round_id/remove/:contestant_id' => 'rounds#remove', :as => :round_remove
	get		'rounds/round/:round_id/save' => 'rounds#save', :as => :round_save
	resources :rounds
	
	get		'contestants/season/:season_id' => 'contestants#index', :as => :contestants_season
	post	'contestants' => 'contestants#create'
	get		'contestants/new/:season_id' => 'contestants#new', :as => :new_contestant
	get		'contestants/:id' => 'contestants#display', :as => :contestant
	post	'contestants/:id' => 'contestants#update'
	delete 'contestants/:id' => 'contestants#destroy'

	get		'login' => 'sessions#new'
	post	'login' => 'sessions#login_attempt'
	post	'login/fb' => 'sessions#facebook_login', :as => :facebook_login
	delete 'login' => 'sessions#logout'

	get		'admin' => 'admin#home'

	# all shows and all seasons lists
	get		'admin/shows' => 'admin#shows', :as => :admin_shows
	get		'admin/seasons' => 'admin#seasons', :as => :admin_seasons

	# API for pulling lists via AJAX
	get		'api/shows'				=> 'application#shows_list',			:as => :api_shows
	get		'api/seasons'			=> 'application#seasons_list',		:as => :api_seasons
	get		'api/episodes'		=> 'application#episodes_list', 	:as => :api_episodes
	get		'api/contestants'	=> 'application#contestants_list', :as => :api_contestants
	get		'api/schemes' 		=> 'application#schemes_list', 		:as => :api_schemes
end

app/models/scheme.rb
# == Schema Information
#
# Table name: schemes
#
#  id          :integer          not null, primary key
#  type        :string(255)
#  description :string(255)
#  points_asgn :integer
#  created_at  :datetime
#  updated_at  :datetime
#  show_id     :integer
#

class Scheme < ActiveRecord::Base
	belongs_to :show, inverse_of: :schemes

	has_many :events
	has_many :contestants, through: :events
	has_many :episodes, through: :events
	has_and_belongs_to_many :leagues
	has_and_belongs_to_many :shows

	validates :type, presence: true, allow_blank: false
	validates :description, presence: true, allow_blank: false
	validates :points_asgn, presence: true, allow_blank: false
	
	before_destroy :scheme_with_show?, :scheme_with_event?
	# cannot delete scheme if shows/events attached

	def scheme_with_show?
		errors[:base] << "Cannot delete scheme with shows."
		return false if self.shows.any?
	end

	def scheme_with_event?
		errors[:base] <<  "Cannot delete scheme with events."
		return false if self.events.any?
	end

	def assign_shows(show_ids)
		linked_shows = []
		nonlinked_shows = []
		shows = Show.all
		shows.each do |show|
			if show_ids && ( show_ids.include? show.id.to_s )
				linked_shows << show 
			else
				nonlinked_shows << show
			end
		end
		nonlinked_shows.each {|show| self.shows.delete(show)}
		linked_shows.each {|show| self.shows << show unless self.shows.include? show}
	end

	private

	def self.filter_search(queries_hash)
		scenario = []
		results = []

		# 1.A If either queries exist, then proceed
		if queries_hash[:show_id] || queries_hash[:type]
			# 1.A.A If YES show_id
			if queries_hash[:show_id]
				show = Show.find(queries_hash[:show_id])
				# 1.A.A.A YES show_id && YES type
				if queries_hash[:type].present?
					schemes = show.schemes.order(type: :asc, description: :asc, points_asgn: :asc).select{|scheme| scheme.type == queries_hash[:type]}
				# 1.A.A.B YES show_id && NO type
				else
					schemes = show.schemes.order(type: :asc, description: :asc, points_asgn: :asc)
				end
			# 1.A.B If NO show_id 
			else
				# NO show_id, YES type
				if queries_hash[:type].present?
					schemes = Scheme.where(type: queries_hash[:type]).order(type: :asc, description: :asc, points_asgn: :asc)
				end
			end
		# 1.B If both queries are "All"
		else
			schemes = Scheme.all.order(type: :asc, description: :asc, points_asgn: :asc)
		end
		results = schemes
	end

	def self.select_scheme
		@schemes_list = Scheme.all.each.map {|s| [s.description, s.type, s.id]}
		@schemes_list.unshift(["Select a scheme", nil])
	end

	def self.select_type
		@type_list = Scheme.descendants.map(&:name).sort
		@type_list.unshift(["Select type", nil])
		@type_list.push(["Add new type", nil])
	end

	def self.list_schemes(episode_id)
		show = Episode.find(episode_id).season.show.schemes.order(type: :asc, description: :asc)
	end

	def self.list_types
		@type_list = Scheme.descendants.map(&:name).sort
		@type_list.unshift(["All Schemes", "All"])
	end
end

app/controllers/schemes_controller.rb
class SchemesController < ApplicationController
	layout "admin"

	def index
		@form_header = "New Scheme"
		@shows = Show.all.order(name: :asc)	
		@show_id = nil
		@schemes = Scheme.all.order(type: :asc, description: :asc, points_asgn: :asc)
		@scheme = Scheme.new
	end

	def new
		@scheme = Scheme.new
		render :partial => "form"
	end

	def create
		@scheme = Scheme.new scheme_params
		if @scheme.save	
			@scheme.assign_shows(params[:showIdsList])
			@selected = Scheme.where(:show_id => params[:show_id]).order(type: :asc, points_asgn: :asc, description: :asc)	
			flash[:notice] = "New scheme has been successfully added."
			flash[:color] = "alert-success success"
			respond_to do |format|
				format.json {
					render :json => {
						:schemeList => @selected,
						:scheme_id => @scheme.id,
						:notice => flash[:notice],
						:color => flash[:color]
					}
				}
			end
		elsif @scheme.errors
			flash[:notice] = "Invalid - Please fix the below before submitting:"
			flash[:color] = "alert-warning warning"
			respond_to do |format|
				format.json {
					render :json => {
						:errors => @scheme.errors.full_messages,
						:notice => flash[:notice],
						:color => flash[:color],
						:success => false
					}, :status => 400
				}
			end
		end
	end

	def edit
		@form_header = "Update Scheme"
		scheme = Scheme.find(params[:id])
		shows = Show.all
		scheme_shows = {}

		shows.each_with_index do |show, i| 
			scheme_shows[i] = {}
			scheme_shows[i][:id] = show.id
			if scheme.shows.include? show
				scheme_shows[i][:include] = true
			else
				scheme_shows[i][:include] = false
			end
		end

		respond_to do |format|
			format.json {
				render :json => {
					:scheme => scheme,
					:shows => scheme_shows,
					:type => scheme.type
				}, :status => 200
			}
		end
	end

	def update
		@scheme = Scheme.find(params[:id])
		shows = Show.all
		show_ids = shows.pluck(:id)
		scheme_shows = {}

		shows.each_with_index do |show, i| 
			scheme_shows[i] = {}
			scheme_shows[i][:id] = show.id
			if @scheme.shows.include? show
				scheme_shows[i][:include] = true
			else
				scheme_shows[i][:include] = false
			end
		end

		if @scheme.update scheme_params
			@schemes = Scheme.all.order(type: :asc, description: :asc, points_asgn: :asc)
			flash[:notice] = "Scheme has been successfully updated."
			flash[:color] = "alert-success success"
			respond_to do |format|
				format.html { render partial: "display_schemes", locals: {schemes: @schemes} }
				format.json {
					render :json => {
						:scheme => @scheme,
						:type => @scheme.type,
						:shows => @scheme.scheme_shows,
						:notice => flash[:notice],
						:color => flash[:color]
					}, :status => 200
				}
			end
		else
			@scheme.errors
			flash[:notice] = "Something went wrong and the scheme was not updated."
			flash[:color] = "alert-warning warning"
			respond_to do |format|
				format.js
				format.json {
					render :json => {
						:scheme => @scheme,
						:type => @scheme.type,
						:notice => flash[:notice],
						:color => flash[:color]
					}, :status => 400
				}
			end	
		end
	end

	def assign
		@scheme = Scheme.find(params[:id])
		@scheme.assign_shows(params[:showIdsList])
		shows = @scheme.shows.pluck(:id)
		flash[:notice] = "Success"
		flash[:color] = "alert alert-success"
		status = 200
		respond_to do |format|
			format.json {
				render :json => {
					:scheme => @scheme,
					:type => @scheme.type,
					:shows => shows,
					:notice => flash[:notice],
					:color => flash[:color]
				}, :status => status
			}
		end	
	end

	def filter
		@show_id = nil
		@scheme_type = nil
		queries_hash = {}

		queries_hash[:show_id] = params[:show_id] unless params[:show_id] == "All"
		queries_hash[:type] = params[:scheme_type] unless params[:scheme_type] == "All"
		
		@schemes = Scheme.filter_search(queries_hash)

		respond_to do |format|
			format.js
		end
	end

	def destroy
		@scheme = Scheme.find params[:id]
		if @scheme.shows.count == 0 && @scheme.events.count == 0
			if @scheme.destroy
				flash[:notice] = "Scheme\##{@scheme.id} has been successfully deleted."
				flash[:color] = "alert alert-success"
			else
				flash[:notice] = "Cannot destroy."
				flash[:color] = "alert alert-danger"
			end
		else
			flash[:notice] = "Delete prohibited. Scheme with shows and/or events cannot be deleted."
			flash[:color] = "alert alert-danger"
		end
		redirect_to schemes_path
	end

	private

	def setSchemeType(params)
		puts params
		if params[:type_select].present?
			case params[:type_select]
			when "Select type"
				params[:scheme][:type] = nil
			when "Add new type"
				params[:scheme][:type] = nil
			else
				params[:scheme][:type] = params[:type_select]
			end
		elsif params[:type_text].present?
			params[:scheme][:type] = params[:type_text]
		else
			return
		end
		return params
	end

	def scheme_params
		setSchemeType(params)
		params.require(:scheme).permit(:id, :type, :description, :points_asgn)
	end
end

app/helpers/schemes_helper.rb
module SchemesHelper

end

app/views/schemes/_display_schemes.html.haml
%table.table.table-hover.table-scroll
	%thead
		%th.col-lg-1 Type
		%th.col-lg-5{"data-field" => "event", "data-sortable" => "true"} Event
		%th.col-lg-1{"data-field" => "points_asgn", "data-sortable" => "true"} Points
		%th.col-lg-3 Actions
	%tbody#schemes_table
		= render partial: "schemes_list", locals: {schemes: schemes}

app/views/schemes/_form.html.haml
%h4= @form_header
= form_for(@scheme, remote: true) do |f|
	#form_alert
	.form-group.field#scheme_form_type
		= f.label :type
		%br/
		= select_tag :type, options_for_select(Scheme.select_type), {name: "type_select", id: "scheme_type_dropdown", class: "form-control", placeholder: "Select a type"}
		#scheme_type_value_area
			= f.text_field :type, placeholder: "Input new scheme type", name: "type_text", id: "scheme_type_input", class: "form-control hidden"
	.form-group.field
		= f.label :description
		%br/
		#scheme_description_value_area
			= f.text_area :description,  name: "scheme[description]", id: "scheme_description_input", class: "form-control"
	.form-group.field
		= f.label :points_asgn, "Points assignment"
		%br/
		#scheme_points_asgn_value_area
			= f.number_field :points_asgn, name: "scheme[points_asgn]", id: "scheme_points_asgn_input", class: "form-control", placeholder: 0
	.form-group.field
		.col-lg-12#scheme_shows
			.row
				= label_tag :scheme_shows, "Shows"
			.row#shows_list
				- @shows.each do |show|
					= check_box_tag :scheme_shows, show.id, false, {class: "checkbox_show", "data-scheme-id" => @scheme.id, "data-show-id" => show.id}
					= show.name
					%br/
			.row
				%br/
	.form-group.field
		.col-lg-12#scheme_events
			.row
				= label_tag :scheme_events, "Events"
			.row#events_list
				- @scheme.events.each do |event|
					= check_box_tag :scheme_events, event.id, false, {class: "checkbox_event", "data-scheme-id" => @scheme.id, "data-event-id" => event.id}
					= event.id
					%br/
	.form-group
		.actions
			.btn.btn-md.btn-default.submit-btn{type: "button", name: "create", method: "POST", action: :create, id: "new_scheme_submit"} Create scheme
			.btn.btn-md.btn-default.update-btn{type: "button", name: "update", method: "PATCH", action: :update, id: "update_scheme_submit", style: "display:none"} Update scheme
			.btn.btn-md.btn-default.cancel-btn{type: "button", name: "cancel", method: "GET", action: :cancel, id: "clear_scheme_form"} Cancel

app/views/schemes/_schemes_filter.html.haml
.row#filters
	.col-lg-3= select_tag :show, options_for_select(Show.shows_list), class: "form-control", focus: false
	.col-lg-3= select_tag :scheme_type, options_for_select(Scheme.list_types, "All"), class: "form-control", focus: false

app/views/schemes/_schemes_list.html.haml
- @schemes.each do |scheme|
	%tr
		-# %td
		-# 	= check_box_tag :scheme, "selection", scheme[1], {"data-scheme-id" => scheme[0].id, "data-show-id" => @show_id}
		%td
			%span{"data-name" => "type", "data-pk" => scheme.id}= scheme.type
		%td
			%span{"data-name" => "description", "data-pk" => scheme.id}= scheme.description
		%td
			%span{"data-name" => "points_asgn", "data-pk" => scheme.id}= scheme.points_asgn
		%td
			.btn.btn-xs.btn-default.action.edit{"data-id" => scheme.id} Edit
			= link_to "Delete", scheme_path(scheme.id), method: "DELETE", class: "btn btn-xs btn-default destroy"

app/views/schemes/_types_menu.html.haml
%h5 
	Filter Types
	-# = link_to "All", schemes_path, class: "btn btn-xs btn-default btn-primary", :remote => true	
	-# - @shows.each do |show|
	-# 	= link_to show.name, fetch_schemes_path(show_id: show.id), class: "btn btn-xs btn-default", "data-show-id" => show.id, :remote => true

app/views/schemes/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/schemes/filter.js.erb
$("#schemes_table").html("<%= escape_javascript(render partial: 'schemes_list', locals: { schemes: @schemes } ) %>"); 

app/views/schemes/from_show.js.erb
$("#schemes_table").html("<%= escape_javascript(render partial: 'schemes_list', locals: { schemes: @schemes } ) %>"); 

app/views/schemes/index.html.haml
#manage-schemes
	.col-lg-12
		%h2 Manage Point Schemes
	.col-lg-3#action-panel
		#scheme_form
			= render partial: "form"
	.col-lg-9
		#scheme_action_alert{class: flash[:color]}
			= flash[:notice]
		#filter_panel
			= render "schemes_filter"
		#schemes_board
			= render partial: "display_schemes", locals: { schemes: @schemes }