config/routes.rb
Rails.application.routes.draw do
	root :to => 'pages#home'

	resources :messages

	get		'events/display/:season_id/:episode_id' => 'events#display', :as => :display_events
	get		'events/get_seasons' => 'events#seasons', :as => :get_seasons
	delete 'events/:event_id' => 'events#destroy', :as => :delete_event
	resources :events
	
	get		'episodes' => 'episodes#index', :as => :episodes
	post	'episodes' => 'episodes#create'
	get		'episodes/new' => 'episodes#new', :as => :new_episode
	get		'episodes/new/:season_id' => 'episodes#new'
	get		'episodes/:id' => 'episodes#display', :as => :episode

	get		'pages/about' => 'pages#about'

	get		'statuses/' => 'statuses#index', :as => :statuses
	get		'statuses/:season_id' => 'statuses#display', :as => :statuses_display

	post 	'schemes/:id/assign' => 'schemes#assign'
	get		'schemes/' => 'schemes#index', as: 'schemes'
	get 	'schemes/fetch_schemes' => 'schemes#filter', as: 'fetch_schemes'
	resources :schemes

	get		'seasons/search' => 'seasons#search'
	get		'seasons' => 'seasons#index', :as => :seasons
	post	'seasons' => 'seasons#create'
	get		'seasons/new/:show_id' => 'seasons#new', :as => :new_season_show
	get		'seasons/new' => 'seasons#new', :as => :new_season
	get		'seasons/:id/edit' => 'seasons#edit', :as => :edit_season
	patch 'seasons/:id/publish' => 'seasons#publish', :as => :publish_season
	patch 'seasons/:id/unpublish' => 'seasons#unpublish', :as => :unpublish_season
	get		'seasons/:id' => 'seasons#display', :as => :season
	patch 'seasons/:id' => 'seasons#update'
	put		'seasons/:id' => 'seasons#update'
	delete 'seasons/:id' => 'seasons#destroy'

	get		'shows/new' => 'shows#new', :as => :new_show
	get		'shows/:id' => 'shows#display', :as => :show
	resources :shows

	get		'leagues/new' => 'leagues#new', :as => :new_league
	get		'leagues' => 'leagues#index', :as => :leagues
	get		'leagues/search' => 'leagues#search'
	get		'leagues/:id/invite' => 'leagues#invite', :as => :league_invite
	get		'leagues/:id' => 'leagues#display', :as => :league
	get		'leagues/:id/schemes' => 'leagues#manage_schemes', :as => :league_schemes
	post	'leagues/:id/schemes/:scheme_id' => 'leagues#scheme_action', :as => :league_scheme_action
	resources :leagues
	resources :fantasies, path: 'leagues', :controller => 'leagues'
	post		'leagues/access' => 'leagues#access', :as => :league_access

	post	'users/signup_fb' => 'users#fb_create', :as => :fb_create	
	post	'users/:id/link_fb' => 'users#link_fb', :as => :link_fb
	post	'users/:id/unlink_fb' => 'users#unlink_fb', :as => :unlink_fb
	resources :users
	resources :messages
	
	post	'rosters/:roster_id/add/:contestant_id' => 'rosters#add', :as => :roster_add
	post	'rosters/:roster_id/remove/:contestant_id' => 'rosters#remove', :as => :roster_remove
	get		'rosters/:roster_id/current' => 'rosters#current', :as => :roster_current
	post	'rosters/:league_id' => 'rosters#create', :as => :rosters
	get		'rosters' => 'rosters#index'
	get		'rosters/new' => 'rosters#new', :as => :new_roster
	get		'rosters/:roster_id/edit' => 'rosters#edit', :as => :roster_edit
	get		'rosters/:id' => 'rosters#display', :as => :roster
	patch 'rosters/:id' => 'rosters#update'
	put		'rosters/:id' => 'rosters#update'
	delete 'rosters/:id' => 'rosters#destroy'

	post	'rounds/:league_id' => 'rounds#create', :as => :rounds_create
	get		'rounds/:league_id/:user_id' => 'rounds#index', :as => :rounds
	get		'rounds/:round_id' => 'rounds#display', :as => :round_display
	get		'rounds/:round_id/edit' => 'rounds#edit', :as => :round_edit
	post	'rounds/:round_id/add/:contestant_id' => 'rounds#add', :as => :round_add
	post	'rounds/:round_id/bulk' => 'rounds#bulk_add', :as => :round_bulk_add
	post	'rounds/:round_id/remove/:contestant_id' => 'rounds#remove', :as => :round_remove
	get		'rounds/round/:round_id/save' => 'rounds#save', :as => :round_save
	resources :rounds
	
	get		'contestants/season/:season_id' => 'contestants#index', :as => :contestants_season
	post	'contestants' => 'contestants#create'
	get		'contestants/new/:season_id' => 'contestants#new', :as => :new_contestant
	get		'contestants/:id' => 'contestants#display', :as => :contestant
	post	'contestants/:id' => 'contestants#update'
	delete 'contestants/:id' => 'contestants#destroy'

	get		'login' => 'sessions#new'
	post	'login' => 'sessions#login_attempt'
	post	'login/fb' => 'sessions#facebook_login', :as => :facebook_login
	delete 'login' => 'sessions#logout'

	get		'admin' => 'admin#home'

	# all shows and all seasons lists
	get		'admin/shows' => 'admin#shows', :as => :admin_shows
	get		'admin/seasons' => 'admin#seasons', :as => :admin_seasons

	# API for pulling lists via AJAX
	get		'api/shows'				=> 'application#shows_list',			:as => :api_shows
	get		'api/seasons'			=> 'application#seasons_list',		:as => :api_seasons
	get		'api/episodes'		=> 'application#episodes_list', 	:as => :api_episodes
	get		'api/contestants'	=> 'application#contestants_list', :as => :api_contestants
	get		'api/schemes' 		=> 'application#schemes_list', 		:as => :api_schemes
end

app/views/admin/_all_shows.html.haml
%h2 All Shows & Seasons
%table.table.table-bordered
	%thead
		%tr
			%th Show
			%th Season
			%th #
			%th Expired
			%th Premiere
			%th Finale
			%th Published
	%tbody.searchable
	- @shows.each do |show|
		- show.seasons.each do |season|	
			%tr
				%td
					= show.name
				%td
					= season.name
				%td 
					= season.number
				%td
					- if season.expired == true
						True
				%td
					= season.premiere_date
				%td
					= season.finale_date
				%td
					= season.published			

app/views/admin/home.html.haml
.panel
	.panel-body
		.col-lg-12
			= render partial: "all_shows"
			%h1 Live Tracking
			= link_to("Events", events_path)
			%h1 All Leagues
			- @leagues.each do |league|
				%p
					= league.name
			%h1 All Users
			%table
				%tbody
					%tr
						%td User Count
						%td 
							= @users.count
					%tr
						%td Active Users
						%td ??
					%tr
						%td Avg. league/user
						%td ??
			%table.table.table-hover
				%thead
					%tr
						%th Username
						%th Email
						%th Joined On
						%th Last Updated
				%tbody
					- @users.each do |user|
						%tr
							%td
								= user.username
							%td
								= user.email
							%td
								= user.created_at
							%td 
								= user.updated_at

app/views/admin/seasons.html.haml
.panel.panel-default
	.panel-body
		.col-lg-10
			%h2 Manage Seasons
		.col-lg-2.text-right
			= link_to "Add New Season", new_season_path, class: "btn btn-default btn-sm"
		.col-lg-12#current-seasons
			%table.table.table-condensed.table-hover
				-# Error Messages
				- if flash[:notice]
					.row.form-group
						.alert{class: flash[:color]}
						= flash[:notice]
				-# End Error Messages
				%h4 
					Current 
					= pluralize_without_count(@current_seasons.count, "Season", text = nil)
				%thead
					%tr
						%th.col-sm-3 Season Name
						%th.col-sm-1 Status
						%th.col-sm-1 Premiere
						%th.col-sm-1 Finale
						%th.col-sm-1 Actions
						%th.col-sm-1 Episodes
						%th.col-sm-1 Contestants
						%th.col-sm-1 Events
				%tbody
					- @current_seasons.each do |season|
						%tr
							/ column 1
							%td
								= link_to "#{season.full_name}", season_path(season.id)
								%br/
								%p #{ season.episodes.count } out of #{ season.episode_count } episodes recorded.
							/ column 2
							%td
								/ PUBLISH SEASON
								- if season.published? 
									- if season.premiere_date.future?
										= link_to "Unpublish", unpublish_season_path(season.id), :method => "patch", :data => {:confirm => "Are you sure you want to unpublish this season?"}, class: "btn btn-xs btn-default btn-block"
										Preshow
									- else
										= link_to "Unpublish", unpublish_season_path(season.id), :method => "patch", :data => {:confirm => "Are you sure you want to unpublish this season?"}, class: "btn btn-xs btn-default btn-block disabled"
										Commenced
								- else
									= link_to "Publish", publish_season_path(season.id), :method => "patch", class:"btn btn-xs btn-primary btn-block"
							%td= season.premiere_date.strftime("%D %l:%M %p %Z")
							/ column 3
							%td= season.finale_date.strftime("%D")
							%td
								= link_to "View", season_path(season.id), class:"btn btn-xs btn-default btn-block"
								= link_to "Edit", edit_season_path(season.id), class:"btn btn-xs btn-default btn-block"
								- if season.premiere_date.future?
									= link_to "Delete", season_path(season.id), :method => "delete", :action => "destroy", :data => {:confirm => "Are you sure you want to delete this season?"}, class: "btn btn-xs btn-default btn-block"
								- else 
									= link_to "Delete", season_path(season.id), :method => "delete", :action => "destroy", :data => {:confirm => "Are you sure you want to delete this season?"}, class: "btn btn-xs btn-default btn-block disabled"
							%td
								= link_to "View All", episodes_path(season.id), class: "btn btn-xs btn-default btn-block"
								= link_to "Add New", new_episode_path(season.id), class: "btn btn-xs btn-default btn-block"
							%td
								= link_to "View", contestants_season_path(season.id), class: "btn btn-xs btn-default btn-block"
								= link_to "Add", new_contestant_path(season.id), class: "btn btn-default btn-xs btn-block"
								= link_to "Edit", contestants_season_path(season.id), class: "btn btn-default btn-xs btn-block"
							%td 
								= link_to "View", season_path(season.id), class: "btn btn-xs btn-default btn-block"
								= link_to "Track", edit_season_path(season.id), class: "btn btn-xs btn-default btn-block"
		.col-lg-12#past-seasons
			%table.table.table-hover
				%h4 
					Past 
					= pluralize_without_count(@past_seasons.count, "Season", text = nil)
				%thead
					%tr
						/ column 1
						%th.col-sm-3 Season Name
						/ column 2
						%th.col-sm-1 Status
						/ column 3
						%th.col-sm-1 Premiered
						/ column 4
						%th.col-sm-1 Finale Date
						/ column 5
						%th.col-sm-3 Actions
						/ column 6
						%th.col-sm-3 Statistics
				%tbody
					- @past_seasons.each do |season|
						%tr
							/ column 1
							%td
								= link_to "#{season.full_name}", season_path(season.id)
							/ column 2
							%td
								- if season.expired == true
									Completed
								- else
									- if season.premiere_date < @current_date
										Commenced
									- elsif season.published? == false
										Unpublished
									- else
										Draft Open
							/ column 3
							%td= season.premiere_date.strftime("%D")
							/ column 4
							%td= season.finale_date.strftime("%D")
							/ column 5
							%td
								= link_to "View", season_path(season.id), class: "btn btn-sm btn-default"
								= link_to "Edit", edit_season_path(season.id), class: "btn btn-sm btn-default"
								= link_to "Contestants", contestants_season_path(season.id), class: "btn btn-sm btn-default"
							%td

app/views/admin/shows.html.haml
.panel.panel-default.col-lg-6
	.panel-body
		.row
			.col-lg-6
				%h2 All Shows
			.col-lg-6.text-right
				= link_to "Add new show", new_show_path, class:"btn btn-default btn-sm"
		.row
			.col-lg-12
				%table.table.table-hover
					%thead
						%tr
							%th.col-lg-3 Shows List
							%th.col-lg-5
							%th.col-lg-4 Actions
					%tbody
						- @shows.each do |show|
							%tr
								%td= link_to show.name, show_path(show.id)
								%td
									- show.seasons.order("number DESC").each do |season|
										- if season.expired
											= link_to "Season #{season.number}", season_path(season.id), class:"btn btn-default btn-xs"
										- else
											= link_to "Season #{season.number}", season_path(season.id), class:"btn btn-primary btn-xs"
								%td
									= link_to "Edit", edit_show_path(show.id), class:"btn btn-default btn-sm"
									= link_to "Add Season", new_season_show_path(show.id), class:"btn btn-default btn-sm"